from . import ir_http
from . import page_visit
from . import stats_service
from . import res_company
from . import res_config_settings
from . import faq
from . import news
from . import news_article_generator
from . import calientes_generator
from . import grupos_dia_semana_generator
from . import materialized_views
from . import lottery_output
from . import lottery_prediction
from . import lottery_curiosity
from . import consulta_combinaciones
from . import patron_atraso
from . import lottery_tabla_acompanantes_cache
from . import lottery_tabla_acompanantes
from . import quiniela_uy_resultados
from . import quiniela_uy_tombola
from . import quiniela_uy_ternas
from . import lottery_sorteo
from . import website_menu
