from . import stats_service
from . import res_company
from . import res_config_settings
from . import faq
from . import news
from . import news_article_generator
from . import calientes_generator
from . import grupos_dia_semana_generator
from . import materialized_views
from . import lottery_output
from . import lottery_sorteo
from . import website_menu
