{
    "name": "Portal",
    "version": "1.1",
    "author": "SeuS IT",
    "category": "Website",
    "summary": "Estadísticas de Lotería",
    "depends": [
        "website",
        "portal",
        "lottery_delays_number",
        "lottery_fireball"
    ],
    "data": [
        'security/ir.model.access.csv',
        "data/faq_data.xml",
        "data/lottery_matviews.sql",
        "data/news_category_data.xml",
        "data/ir_cron.xml",
        "views/page_visit_views.xml",
        "views/estadisticas_grupos.xml",
        "views/grupos_por_dia.xml",
        "views/estadisticas_numeros.xml",
        "views/estadisticas_pintas.xml",
        "views/homepage_template.xml",
        "views/news_template.xml",
        "views/news_admin.xml",
        "views/faq_template.xml",
        "views/faq_views.xml",
        "views/politica_privacidad.xml",
        "views/terminos_condiciones.xml",
        "views/buscador_publico_template.xml",
        "views/maintenance_template.xml",
        "views/contactus.xml",
        "views/website_layout.xml",
        "views/res_config_settings.xml",
        "views/menu.xml",
        "views/lottery_output_validation_views.xml",
        "views/lottery_prediction_views.xml",
        "views/lottery_curiosity_views.xml",
        "views/lottery_sorteo_views.xml",
    ],
    'assets': {
        'web.assets_frontend': [
            'lottery_portal/static/src/css/news.css',
            'lottery_portal/static/src/css/homepage.css',
            'lottery_portal/static/src/css/dashboard_numbers.css',
            'lottery_portal/static/src/css/dashboard_groups.css',
            'lottery_portal/static/src/css/dashboard_pintas.css',
            'lottery_portal/static/src/scss/faq.scss',
            'lottery_portal/static/src/scss/legal.scss',
            'lottery_portal/static/src/scss/contactus.scss',
            'lottery_portal/static/src/scss/footer.scss',
            'lottery_portal/static/src/scss/sorteo_selector.scss',
            'lottery_portal/static/src/scss/buscador_publico.scss',
            'lottery_portal/static/src/js/Chart.js',
            'lottery_portal/static/src/js/chartjs-plugin-datalabels.js',
            'lottery_portal/static/src/js/chart_init.js',
            'lottery_portal/static/src/js/sorteo_state.js',
            'lottery_portal/static/src/js/sorteo_selector.js',
            'lottery_portal/static/src/js/faq.js',
            'lottery_portal/static/src/js/top10_by_day.js',
            'lottery_portal/static/src/js/top_atrasos.js',
            'lottery_portal/static/src/js/ultimas_salidas_day.js',
            'lottery_portal/static/src/js/ultimas_salidas_consecutivas.js',
            'lottery_portal/static/src/js/ultimas_salidas_col1.js',
            'lottery_portal/static/src/js/buscar_salida.js',
            'lottery_portal/static/src/js/buscador_publico.js',
            'lottery_portal/static/src/js/top5_centenas_atrasadas.js',
            'lottery_portal/static/src/js/top5_bola_extra_atrasadas.js',
            'lottery_portal/static/src/js/top_atrasos_lineas.js',
            'lottery_portal/static/src/js/top_atrasos_terminales.js',
            'lottery_portal/static/src/js/top_atrasos_parejas.js',
            'lottery_portal/static/src/js/lottery_dashboard_numbers.js',
            'lottery_portal/static/src/js/lottery_dashboard_groups.js',
            'lottery_portal/static/src/js/lottery_dashboard_pintas.js',
            'lottery_portal/static/src/js/numeros_calientes.js',
            'lottery_portal/static/src/js/lottery_weekend_groups.js',
            'lottery_portal/static/src/js/grupos_por_dia.js',
            'lottery_portal/static/src/js/lottery_sequences.js',
            'lottery_portal/static/src/js/consultar_acompanantes.js',
            'lottery_portal/static/src/js/ultimos_resultados.js',
            'lottery_portal/static/src/xml/top10_by_day.xml',
            'lottery_portal/static/src/xml/top_atrasos.xml',
            'lottery_portal/static/src/xml/ultima_salidas_day.xml',
            'lottery_portal/static/src/xml/ultimas_salidas_consecutivas.xml',
            'lottery_portal/static/src/xml/ultimas_salidas_col1.xml',
            'lottery_portal/static/src/xml/buscar_salida.xml',
            'lottery_portal/static/src/xml/buscador_publico.xml',
            'lottery_portal/static/src/xml/top5_centenas_atrasadas.xml',
            'lottery_portal/static/src/xml/top5_bola_extra_atrasadas.xml',
            'lottery_portal/static/src/xml/top_atrasos_lineas.xml',
            'lottery_portal/static/src/xml/top_atrasos_terminales.xml',
            'lottery_portal/static/src/xml/top_atrasos_parejas.xml',
            'lottery_portal/static/src/xml/lottery_dashboard_numbers.xml',
            'lottery_portal/static/src/xml/lottery_dashboard_groups.xml',
            'lottery_portal/static/src/xml/lottery_dashboard_pintas.xml',
            'lottery_portal/static/src/xml/numeros_calientes.xml',
            'lottery_portal/static/src/xml/lottery_weekend_groups.xml',
            'lottery_portal/static/src/xml/grupos_por_dia.xml',
            'lottery_portal/static/src/xml/lottery_sequences.xml',
            'lottery_portal/static/src/xml/consultar_acompanantes.xml',
            'lottery_portal/static/src/xml/faq.xml',
            'lottery_portal/static/src/xml/sorteo_selector.xml',
            'lottery_portal/static/src/xml/ultimos_resultados.xml',
        ],
    },
    "installable": True,
    "application": False,
}
