{
    "name": "Portal",
    "version": '2.0',
    "author": "SeuS IT",
    "category": "Website",
    "summary": "Estadísticas de Lotería",
    "depends": [
        "website",
        "portal",
        "lottery_delays_number",
        "lottery_fireball",
        "lottery_tombola_delays",
        "lottery_groups"
    ],
    "data": [
        'security/ir.model.access.csv',
        "data/faq_data.xml",
        "data/ir_cron.xml",
        "views/faq_template.xml",
        "views/faq_views.xml",
        "views/politica_privacidad.xml",
        "views/terminos_condiciones.xml",
        "views/buscador_publico_template.xml",
        "views/maintenance_template.xml",
        "views/contactus.xml",
        "views/website_layout.xml",
        "views/res_config_settings.xml",
        "views/menu.xml",
        # Después de menu.xml: su menú cuelga de menu_faq_root.
        "views/page_visit_views.xml",
        "views/lottery_output_validation_views.xml",
        "views/lottery_prediction_views.xml",
        "views/numeros_suerte_views.xml",
        "views/consulta_combinaciones_views.xml",
        "views/patron_atraso_views.xml",
        "views/lottery_tabla_acompanantes_views.xml",
        "views/quiniela_uy_resultados_views.xml",
        "views/quiniela_uy_tombola_views.xml",
        "views/quiniela_uy_ternas_views.xml",
        "views/lottery_curiosity_views.xml",
        "views/lottery_sorteo_views.xml",
    ],
    'assets': {
        'web.assets_frontend': [
            'lottery_portal/static/src/css/homepage.css',
            'lottery_portal/static/src/scss/faq.scss',
            'lottery_portal/static/src/scss/legal.scss',
            'lottery_portal/static/src/scss/contactus.scss',
            'lottery_portal/static/src/scss/footer.scss',
            'lottery_portal/static/src/scss/buscador_publico.scss',
            'lottery_portal/static/src/js/faq.js',
            'lottery_portal/static/src/js/buscador_publico.js',
            'lottery_portal/static/src/xml/faq.xml',
            'lottery_portal/static/src/xml/buscador_publico.xml',
        ],
    },
    "installable": True,
    "application": False,
}
