{
    "name": "Portal",
    "version": "1.0",
    "author": "SeuS IT",
    "category": "Website",
    "summary": "Estadísticas de Lotería",
    "depends": [
        "website",
        "portal",
        "lottery_delays_number",
        "lottery_fireball"
    ],
    "data": [
        'security/ir.model.access.csv',
        "data/faq_data.xml",
        "data/lottery_matviews.sql",
        "views/estadisticas_grupos.xml",
        "views/estadisticas_numeros.xml",
        "views/estadisticas_pintas.xml",
        "views/homepage_template.xml",
        "views/faq_template.xml",
        "views/faq_views.xml",
        "views/politica_privacidad.xml",
        "views/terminos_condiciones.xml",
        "views/website_layout.xml",
        "views/res_config_settings.xml",
        "views/menu.xml",
    ],
    'assets': {
        'web.assets_frontend': [
            'lottery_portal/static/src/css/homepage.css',
            'lottery_portal/static/src/css/dashboard_numbers.css',
            'lottery_portal/static/src/css/dashboard_groups.css',
            'lottery_portal/static/src/css/dashboard_pintas.css',
            'lottery_portal/static/src/scss/faq.scss',
            'lottery_portal/static/src/js/Chart.js',
            'lottery_portal/static/src/js/chartjs-plugin-datalabels.js',
            'lottery_portal/static/src/js/chart_init.js',
            'lottery_portal/static/src/js/faq.js',
            'lottery_portal/static/src/js/top10_by_day.js',
            'lottery_portal/static/src/js/top_atrasos.js',
            'lottery_portal/static/src/js/ultimas_salidas_day.js',
            'lottery_portal/static/src/js/buscar_salida.js',
            'lottery_portal/static/src/js/top5_centenas_atrasadas.js',
            'lottery_portal/static/src/js/top5_bola_extra_atrasadas.js',
            'lottery_portal/static/src/js/top_atrasos_lineas.js',
            'lottery_portal/static/src/js/top_atrasos_terminales.js',
            'lottery_portal/static/src/js/top_atrasos_parejas.js',
            'lottery_portal/static/src/js/lottery_dashboard_numbers.js',
            'lottery_portal/static/src/js/lottery_dashboard_groups.js',
            'lottery_portal/static/src/js/lottery_dashboard_pintas.js',
            'lottery_portal/static/src/xml/top10_by_day.xml',
            'lottery_portal/static/src/xml/top_atrasos.xml',
            'lottery_portal/static/src/xml/ultima_salidas_day.xml',
            'lottery_portal/static/src/xml/buscar_salida.xml',
            'lottery_portal/static/src/xml/top5_centenas_atrasadas.xml',
            'lottery_portal/static/src/xml/top5_bola_extra_atrasadas.xml',
            'lottery_portal/static/src/xml/top_atrasos_lineas.xml',
            'lottery_portal/static/src/xml/top_atrasos_terminales.xml',
            'lottery_portal/static/src/xml/top_atrasos_parejas.xml',
            'lottery_portal/static/src/xml/lottery_dashboard_numbers.xml',
            'lottery_portal/static/src/xml/lottery_dashboard_groups.xml',
            'lottery_portal/static/src/xml/lottery_dashboard_pintas.xml',
            'lottery_portal/static/src/xml/faq.xml',
        ],
    },
    "installable": True,
    "application": False,
}
