{
    'name': 'Base',
    'version': '0.2',
    'description': """º
Configuraciones iniciales
""",
    'author': 'SeuS IT',
    'category': 'Loterías',
    'maintainer': 'SeuS IT',
    'license': 'LGPL-3',
    'depends': ['base'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/lottery_rules.xml',
        'data/lottery_sorteo_data.xml',
        'data/lottery_number_data.xml',
        'data/lottery_output_sorteo_filters_data.xml',
        'data/lottery_output_1988_data.xml',
        'data/lottery_output_1989_data.xml',
        'data/lottery_output_1990_data.xml',
        'data/lottery_output_1991_data.xml',
        'data/lottery_output_1992_data.xml',
        'data/lottery_output_1993_data.xml',
        'data/lottery_output_1994_data.xml',
        'data/lottery_output_1995_data.xml',
        'data/lottery_output_1996_data.xml',
        'data/lottery_output_1997_data.xml',
        'data/lottery_output_1998_data.xml',
        'data/lottery_output_1999_data.xml',
        'data/lottery_output_2000_data.xml',
        'data/lottery_output_2001_data.xml',
        'data/lottery_output_2002_data.xml',
        'data/lottery_output_2003_data.xml',
        'data/lottery_output_2004_data.xml',
        'data/lottery_output_2005_data.xml',
        'data/lottery_output_2006_data.xml',
        'data/lottery_output_2007_data.xml',
        'data/lottery_output_2008_05_18_data.xml',
        'data/lottery_output_2008_05_19_data.xml',
        'data/lottery_output_2009_data.xml',
        'data/lottery_output_2010_data.xml',
        'data/lottery_output_2011_data.xml',
        'data/lottery_output_2012_data.xml',
        'data/lottery_output_2013_data.xml',
        'data/lottery_output_2014_data.xml',
        'data/lottery_output_2015_data.xml',
        'data/lottery_output_2016_data.xml',
        'data/lottery_output_2017_data.xml',
        'data/lottery_output_2018_data.xml',
        'data/lottery_output_2019_data.xml',
        'data/lottery_output_2020_data.xml',
        'data/lottery_output_2021_data.xml',
        'data/lottery_output_2022_data.xml',
        'data/lottery_output_2023_data.xml',
        'data/lottery_output_2024_data.xml',
        'data/lottery_output_2025_data.xml',
        'data/lottery_output_2026_data.xml',
        'views/lottery_number_view.xml',
        'views/lottery_sorteo_view.xml',
        'views/lottery_output_view.xml',
        'views/lottery_menu_view.xml',
        'views/res_users_view.xml',
    ],
    'installable': True,
    'post_init_hook': 'post_init_hook',

}
